stack-examples: Fix projectRepo ref example
pulumi/pulumi-kubernetes-operator pull request #386
Opened 2022-12-19 21:17 UTC by stevesloka

### Proposed changes

When following the example yaml implementation (https://github.com/pulumi/pulumi-kubernetes-operator/blob/master/docs/create-stacks-using-kubectl.md#nginx-deployment) it uses the projectRepo (https://github.com/metral/pulumi-nginx) which has a sample nginx deployment and is very out of date.

When running this example, I ended up with the following errors in the operator:
```
{"level":"error","ts":1671481232.6940339,"logger":"controller_stack","msg":"Failed to update Stack","Request.Namespace":"pulumi","Request.Name":"nginx-k8s-stack","Stack.Name":"stevesloka/nginx/dev","error":"installing project dependencies: exit status 1","stacktrace":"github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack.(*ReconcileStack).Reconcile\n\t/Users/stevesloka/godev/src/github.com/pulumi/pulumi-kubernetes-operator/pkg/controller/stack/stack_controller.go:462\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/Users/stevesloka/godev/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/stevesloka/godev/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/stevesloka/godev/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
```

It turns out that the deps are so old that `npm install` failed which matches the error (e.g. `exit 1`), but wasn't quite apparent.

I forked the repo and updated my deps and it works fine now: https://github.com/stevesloka/pulumi-nginx

Maybe we should move this to pulumi/examples so it's better maintained?

### Related issues (optional)

Fixes #385

Signed-off-by: Steve Sloka <steve@pulumi.com>

2022-12-20 10:57 UTC, danielrbradley commented
Just briefly looking over this as part of initial triage. We might not want to link to a personal GH org. Could we put this associated repo somewhere under Pulumi's control?

2022-12-20 12:06 UTC, dirien requested changes
Why not use https://github.com/pulumi/examples/blob/master/kubernetes-ts-nginx?

Two birds with one stone?

2022-12-20 16:11 UTC, stevesloka commented
@danielrbradley @dirien thanks for the suggestions. I figured we'd want to use the examples repo. I updated to use the `kubernetes-ts-nginx` example.

2022-12-20 17:40 UTC, dirien approved these changes
LGTM!

2023-01-03 14:49 UTC, squaremo commented
Looks sensible, thank you. Extra points for putting an explanation in the commit message 😄

You could just `rebase -i` this into one commit, since the second commit is a fixup of the first. It'll get squashed into the default branch, but it's good to have the habit of keeping a tidy git history for when people come looking. (Having made the suggestion -- I'll merge it either way)

2023-02-15 12:54 UTC, merged