Refactor controller to use Automation API
pulumi/pulumi-kubernetes-operator pull request #86
Opened 2020-08-27 16:56 UTC by metral

### Proposed changes

Refactor controller to use Automation API

### Related issues (optional)

Closes #85

2020-09-09 17:20 UTC, lblackstone requested changes
Looking good overall! Since it looks like the automation API doesn't support a few existing features yet, do we want to hold off on this, or is it better to move ahead with the refactor?

2020-09-09 17:20 UTC, lblackstone commented on pkg/controller/stack/stack_controller.go
> +			cmd.Env = append(cmd.Env, strings.Join(e, "="))
```suggestion
			cmd.Env = append(cmd.Env, strings.Sprintf("%s=%s", k, v))
```

2020-09-09 17:20 UTC, lblackstone commented on pkg/controller/stack/stack_controller.go
> +		value := apiextensionsv1.JSON{}
```suggestion
		var value apiextensionsv1.JSON
```

2020-09-09 17:20 UTC, lblackstone commented on pkg/controller/stack/stack_controller.go
> +	substr = strings.TrimSuffix(substr, "\n")
```suggestion
	substr := permalinkStart[:end[1]-1]
```

2020-09-09 18:37 UTC, EvanBoyle commented
I believe the secrets provider work is the last big TODO for automation API and we should have feature parity after that. I'm not opposed to holding off until that lands.

2020-09-09 19:18 UTC, metral commented
> do we want to hold off on this, or is it better to move ahead with the refactor?

> I'm not opposed to holding off until that lands.

Thanks for the review! Holding off SGTM 👍

2020-09-15 19:06 UTC, lblackstone approved these changes
🎉  Looks awesome!

2020-09-15 21:02 UTC, EvanBoyle approved these changes
This looks great! Awesome to see so much red! 🚀 

One thing I noticed was that there is a small regression in functionality. Previously `pulumi up` and company were being run through the `runCmd` func which has it's own io handling to pipe stdout to logs that can be followed by kubectl and such:

https://github.com/pulumi/pulumi-kubernetes-operator/blob/6a4943af8b888adcf3f7fc2b0400f57768a0dcf7/pkg/controller/stack/stack_controller.go#L500-L530

Given that updates are run through automation API, those logs won't flow anymore. A solution here is to wire up `ProgressStreams` from this PR https://github.com/pulumi/pulumi/pull/5367 for up/refresh/destroy/preview with the `io.Writer` from the logging interface (not sure if that's a logging interface or if it just goes to stdout). Not blocking, but something to consider.

2020-09-15 22:29 UTC, metral commented on pkg/controller/stack/stack_controller.go
> +	sess.autoStack.Workspace().SetEnvVar("PULUMI_ACCESS_TOKEN", sess.accessToken)
Ah good point! I'll move it before stack upsert for the time being until 5370 is addressed.

2020-09-15 22:41 UTC, metral commented
Opened https://github.com/pulumi/pulumi-kubernetes-operator/issues/87 to track the use of `ProgressStreams` for logs.

2020-09-16 01:49 UTC, merged